name: pros make

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v3
      - name: Builds Code
        uses: fishsticks89/pros-build@v1